In [1]:
import torch
import torch.nn as nn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


/Users/berkedenizbozyigit/anaconda3/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
df = pd.read_csv("Data/NYCTaxiFares.csv")

In [3]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
0        40.730521         -73.975499         40.744746                1  
1        40.740558         -73.974232         40.744114                1  
2        40.751118         -73.960064         40.766235                2  
3        40.756422         -73.971205         40.748192                1  
4        40.734202         -73.905956         40.743115                1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   pickup_datetime    120000 non-null  object 
 1   fare_amount        120000 non-null  float64
 2   fare_class         120000 non-null  int64  
 3   pickup_longitude   120000 non-null  float64
 4   pickup_latitude    120000 non-null  float64
 5   dropoff_longitude  120000 non-null  float64
 6   dropoff_latitude   120000 non-null  float64
 7   passenger_count    120000 non-null  int64  
dtypes: float64(5), int64(2), object(1)
memory usage: 7.3+ MB


In [5]:
df.tail()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
119995  2010-04-18 14:33:03 UTC         15.3           1        -73.955857   
119996  2010-04-23 10:27:48 UTC         15.3           1        -73.996329   
119997  2010-04-18 18:50:40 UTC         12.5           1        -73.988574   
119998  2010-04-13 08:14:44 UTC          4.9           0        -74.004449   
119999  2010-04-17 16:00:14 UTC          5.3           0        -73.955415   

        pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
119995        40.784590         -73.981941         40.736789                1  
119996        40.772727         -74.049890         40.740413                1  
119997        40.749772         -74.011541         40.707799                3  
119998        40.724529         -73.992697         40.730765                1  
119999        40.771920         -73.967623         40.763015                3

In [6]:
df['fare_amount'].describe()

count    120000.000000
mean         10.040326
std           7.500134
min           2.500000
25%           5.700000
50%           7.700000
75%          11.300000
max          49.900000
Name: fare_amount, dtype: float64

 ## Calculate the distance traveled
The <a href='https://en.wikipedia.org/wiki/Haversine_formula'>haversine formula</a> calculates the distance on a sphere between two sets of GPS coordinates.<br>
Here we assign latitude values with $\varphi$ (phi) and longitude with $\lambda$ (lambda).

The distance formula works out to

${\displaystyle d=2r\arcsin \left({\sqrt {\sin ^{2}\left({\frac {\varphi _{2}-\varphi _{1}}{2}}\right)+\cos(\varphi _{1})\:\cos(\varphi _{2})\:\sin ^{2}\left({\frac {\lambda _{2}-\lambda _{1}}{2}}\right)}}\right)}$

where

$\begin{split} r&: \textrm {radius of the sphere (Earth's radius averages 6371 km)}\\
\varphi_1, \varphi_2&: \textrm {latitudes of point 1 and point 2}\\
\lambda_1, \lambda_2&: \textrm {longitudes of point 1 and point 2}\end{split}$

In [7]:
def haversine_distance(df, lat1, long1, lat2, long2):
    """
    Calculates the haversine distance between 2 sets of GPS coordinates in df
    """
    r = 6371  # average radius of Earth in kilometers
       
    phi1 = np.radians(df[lat1])
    phi2 = np.radians(df[lat2])
    
    delta_phi = np.radians(df[lat2]-df[lat1])
    delta_lambda = np.radians(df[long2]-df[long1])
     
    a = np.sin(delta_phi/2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    d = (r * c) # in kilometers

    return d

In [8]:
df['dist_km'] = haversine_distance(df,'pickup_latitude', 'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude')
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km  
0  2.126312  
1  1.392307  
2  3.326763  
3  1.864129  
4  7.231321

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   pickup_datetime    120000 non-null  object 
 1   fare_amount        120000 non-null  float64
 2   fare_class         120000 non-null  int64  
 3   pickup_longitude   120000 non-null  float64
 4   pickup_latitude    120000 non-null  float64
 5   dropoff_longitude  120000 non-null  float64
 6   dropoff_latitude   120000 non-null  float64
 7   passenger_count    120000 non-null  int64  
 8   dist_km            120000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 8.2+ MB


In [10]:
df['EDTdate'] = pd.to_datetime(df['pickup_datetime'].str[:19]) - pd.Timedelta(hours=4)
df['Hour'] = df['EDTdate'].dt.hour
df['AMorPM'] = np.where(df['Hour']<12,'am','pm')
df['Weekday'] = df['EDTdate'].dt.strftime("%a")
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km             EDTdate  Hour AMorPM Weekday  
0  2.126312 2010-04-19 04:17:56     4     am     Mon  
1  1.392307 2010-04-17 11:43:53    11     am     Sat  
2  3.326763 2010-04-17 07:23:26     7     am     Sat  
3  1.864129 2010-04-11 17:25:03    17     pm     Sun  
4  7.231321 2010-04-16 22:19:01    22     pm     Fri

In [11]:
df['EDTdate'].min()

Timestamp('2010-04-11 00:00:10')

In [12]:
df['EDTdate'].max()

Timestamp('2010-04-24 23:59:42')

In [13]:
cat_cols = ['Hour', 'AMorPM', 'Weekday']
cont_cols = ['pickup_latitude', 'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude', 'passenger_count', 'dist_km']
y_col = ['fare_amount']  # this column contains the labels

In [14]:
df.dtypes

pickup_datetime              object
fare_amount                 float64
fare_class                    int64
pickup_longitude            float64
pickup_latitude             float64
dropoff_longitude           float64
dropoff_latitude            float64
passenger_count               int64
dist_km                     float64
EDTdate              datetime64[ns]
Hour                          int64
AMorPM                       object
Weekday                      object
dtype: object

In [15]:
for cat in cat_cols:
    df[cat] = df[cat].astype('category')

In [16]:
df.dtypes

pickup_datetime              object
fare_amount                 float64
fare_class                    int64
pickup_longitude            float64
pickup_latitude             float64
dropoff_longitude           float64
dropoff_latitude            float64
passenger_count               int64
dist_km                     float64
EDTdate              datetime64[ns]
Hour                       category
AMorPM                     category
Weekday                    category
dtype: object

In [17]:
df['Hour'].head()

0     4
1    11
2     7
3    17
4    22
Name: Hour, dtype: category
Categories (24, int64): [0, 1, 2, 3, ..., 20, 21, 22, 23]

In [18]:
hr = df['Hour'].cat.codes.values
ampm = df['AMorPM'].cat.codes.values
wkdy = df['Weekday'].cat.codes.values

In [19]:
hr 

array([ 4, 11,  7, ..., 14,  4, 12], dtype=int8)

In [20]:
cats = np.stack([hr,ampm,wkdy],axis=1)

In [21]:
cats

array([[ 4,  0,  1],
       [11,  0,  2],
       [ 7,  0,  2],
       ...,
       [14,  1,  3],
       [ 4,  0,  5],
       [12,  1,  2]], dtype=int8)

In [22]:
cats = np.stack([df[col].cat.codes.values for col in cat_cols],1)

In [23]:
cats = torch.tensor(cats,dtype=torch.int64)

In [24]:
conts =np.stack([df[col].values for col in cont_cols],axis=1)

In [25]:
conts

array([[ 40.730521  , -73.992365  ,  40.744746  , -73.975499  ,
          1.        ,   2.12631159],
       [ 40.740558  , -73.990078  ,  40.744114  , -73.974232  ,
          1.        ,   1.39230687],
       [ 40.751118  , -73.994149  ,  40.766235  , -73.960064  ,
          2.        ,   3.32676344],
       ...,
       [ 40.749772  , -73.988574  ,  40.707799  , -74.011541  ,
          3.        ,   5.05252282],
       [ 40.724529  , -74.004449  ,  40.730765  , -73.992697  ,
          1.        ,   1.20892296],
       [ 40.77192   , -73.955415  ,  40.763015  , -73.967623  ,
          3.        ,   1.42739869]])

In [26]:
conts = torch.tensor(conts, dtype=torch.float)

In [27]:
conts

tensor([[ 40.7305, -73.9924,  40.7447, -73.9755,   1.0000,   2.1263],
        [ 40.7406, -73.9901,  40.7441, -73.9742,   1.0000,   1.3923],
        [ 40.7511, -73.9941,  40.7662, -73.9601,   2.0000,   3.3268],
        ...,
        [ 40.7498, -73.9886,  40.7078, -74.0115,   3.0000,   5.0525],
        [ 40.7245, -74.0044,  40.7308, -73.9927,   1.0000,   1.2089],
        [ 40.7719, -73.9554,  40.7630, -73.9676,   3.0000,   1.4274]])

In [31]:
y = torch.tensor(df[y_col].values,dtype=torch.float).reshape(-1,1)

In [32]:
cats.shape

torch.Size([120000, 3])

In [33]:
conts.shape

torch.Size([120000, 6])

In [34]:
y.shape

torch.Size([120000, 1])

In [35]:
cat_size = [len(df[col].cat.categories) for col in cat_cols]

In [36]:
cat_size

[24, 2, 7]

In [37]:
emb_size = [(size,min(50,(size+1)//2)) for size in cat_size]

In [38]:
emb_size

[(24, 12), (2, 1), (7, 4)]

In [39]:
catz = cats[:4]

In [40]:
catz

tensor([[ 4,  0,  1],
        [11,  0,  2],
        [ 7,  0,  2],
        [17,  1,  3]])

In [42]:
selfembeds = nn.ModuleList([nn.Embedding(ni,nf) for ni,nf in emb_size])

In [43]:
selfembeds

ModuleList(
  (0): Embedding(24, 12)
  (1): Embedding(2, 1)
  (2): Embedding(7, 4)
)

In [44]:
embeddingz = []

for i,e in enumerate(selfembeds):
    embeddingz.append(e(catz[:,i]))

In [45]:
embeddingz

[tensor([[ 1.0325, -1.7337, -0.3517, -0.2156,  1.6509, -0.3791,  0.2631,  1.5028,
          -0.7700,  0.7409,  0.4534, -0.3521],
         [ 0.4867,  0.7857,  1.3771, -1.2154,  1.7635, -0.5119,  0.5086,  0.3139,
          -1.9364,  0.4130, -0.2340, -0.2923],
         [-0.4232,  0.1812, -1.8287, -0.3087, -0.4148, -0.3767, -0.0333,  0.8867,
           0.3249, -0.6121, -0.3356, -1.5467],
         [-0.0143, -1.0927, -0.1606, -2.6754, -0.1541,  0.2564, -0.0149,  1.9968,
           0.9542, -0.8564, -0.9792, -0.7682]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.9647],
         [-0.9647],
         [-0.9647],
         [ 1.0592]], grad_fn=<EmbeddingBackward0>),
 tensor([[ 2.7707,  0.4532, -0.4428,  1.1758],
         [ 0.6174, -0.0273,  1.0741,  1.3366],
         [ 0.6174, -0.0273,  1.0741,  1.3366],
         [-0.7031, -0.0180, -0.1402, -0.6719]], grad_fn=<EmbeddingBackward0>)]

In [46]:
# We concatenate the embedding sections (12,1,4) into one (17)
z = torch.cat(embeddingz, 1)
z

tensor([[ 1.0325, -1.7337, -0.3517, -0.2156,  1.6509, -0.3791,  0.2631,  1.5028,
         -0.7700,  0.7409,  0.4534, -0.3521, -0.9647,  2.7707,  0.4532, -0.4428,
          1.1758],
        [ 0.4867,  0.7857,  1.3771, -1.2154,  1.7635, -0.5119,  0.5086,  0.3139,
         -1.9364,  0.4130, -0.2340, -0.2923, -0.9647,  0.6174, -0.0273,  1.0741,
          1.3366],
        [-0.4232,  0.1812, -1.8287, -0.3087, -0.4148, -0.3767, -0.0333,  0.8867,
          0.3249, -0.6121, -0.3356, -1.5467, -0.9647,  0.6174, -0.0273,  1.0741,
          1.3366],
        [-0.0143, -1.0927, -0.1606, -2.6754, -0.1541,  0.2564, -0.0149,  1.9968,
          0.9542, -0.8564, -0.9792, -0.7682,  1.0592, -0.7031, -0.0180, -0.1402,
         -0.6719]], grad_fn=<CatBackward0>)

In [47]:
# This was assigned under the __init__() method
selfembdrop = nn.Dropout(.4)

In [48]:
z = selfembdrop(z)
z

tensor([[ 1.7209, -2.8895, -0.0000, -0.3594,  2.7514, -0.0000,  0.0000,  2.5047,
         -0.0000,  0.0000,  0.7556, -0.0000, -1.6078,  4.6179,  0.7553, -0.0000,
          1.9596],
        [ 0.0000,  1.3095,  2.2952, -2.0256,  2.9392, -0.0000,  0.0000,  0.0000,
         -0.0000,  0.0000, -0.0000, -0.4871, -0.0000,  0.0000, -0.0455,  1.7902,
          2.2277],
        [-0.7053,  0.3020, -0.0000, -0.5145, -0.6913, -0.0000, -0.0555,  1.4778,
          0.5415, -1.0202, -0.5593, -2.5779, -1.6078,  0.0000, -0.0455,  1.7902,
          0.0000],
        [-0.0000, -0.0000, -0.2677, -4.4590, -0.2568,  0.0000, -0.0000,  3.3280,
          1.5904, -1.4273, -1.6320, -0.0000,  1.7654, -0.0000, -0.0000, -0.0000,
         -0.0000]], grad_fn=<MulBackward0>)

In [49]:
class TabularModel(nn.Module):

    def __init__(self, emb_szs, n_cont, out_sz, layers, p=0.5):
        super().__init__()
        self.embeds = nn.ModuleList([nn.Embedding(ni, nf) for ni,nf in emb_szs])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        
        layerlist = []
        n_emb = sum((nf for ni,nf in emb_szs))
        n_in = n_emb + n_cont
        
        for i in layers:
            layerlist.append(nn.Linear(n_in,i)) 
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
            
        self.layers = nn.Sequential(*layerlist)
    
    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)
        
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x

In [51]:
torch.manual_seed(33)
model = TabularModel(emb_size, conts.shape[1], 1, [200,100], p=0.4)

In [52]:
model

TabularModel(
  (embeds): ModuleList(
    (0): Embedding(24, 12)
    (1): Embedding(2, 1)
    (2): Embedding(7, 4)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=23, out_features=200, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=200, out_features=100, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=100, out_features=1, bias=True)
  )
)

In [53]:
criterion = nn.MSELoss()  
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [54]:
batch_size = 60000
test_size = int(batch_size * .2)

cat_train = cats[:batch_size-test_size]
cat_test = cats[batch_size-test_size:batch_size]
con_train = conts[:batch_size-test_size]
con_test = conts[batch_size-test_size:batch_size]
y_train = y[:batch_size-test_size]
y_test = y[batch_size-test_size:batch_size]

In [55]:
import time
start_time = time.time()

epochs = 300
losses = []

for i in range(epochs):
    i+=1
    y_pred = model(cat_train, con_train)
    loss = torch.sqrt(criterion(y_pred, y_train)) # RMSE
    losses.append(loss)
    
    # a neat trick to save screen space:
    if i%25 == 1:
        print(f'epoch: {i:3}  loss: {loss.item():10.8f}')

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(f'epoch: {i:3}  loss: {loss.item():10.8f}') # print the last line
print(f'\nDuration: {time.time() - start_time:.0f} seconds') # print the time elapsed

epoch:   1  loss: 12.56661701
epoch:  26  loss: 10.91414452
epoch:  51  loss: 10.22180653
epoch:  76  loss: 9.74221516
epoch: 101  loss: 9.18559933
epoch: 126  loss: 8.43100357
epoch: 151  loss: 7.42760420
epoch: 176  loss: 6.23030090
epoch: 201  loss: 5.07308149
epoch: 226  loss: 4.21146965
epoch: 251  loss: 3.89457393
epoch: 276  loss: 3.78478384
epoch: 300  loss: 3.70921564

Duration: 217 seconds


In [57]:
# TO EVALUATE THE ENTIRE TEST SET
with torch.no_grad():
    y_val = model(cat_test, con_test)
    loss = torch.sqrt(criterion(y_val, y_test))
print(f'RMSE: {loss:.8f}')

RMSE: 3.66840959


In [58]:
print(f'{"PREDICTED":>12} {"ACTUAL":>8} {"DIFF":>8}')
for i in range(50):
    diff = np.abs(y_val[i].item()-y_test[i].item())
    print(f'{i+1:2}. {y_val[i].item():8.4f} {y_test[i].item():8.4f} {diff:8.4f}')

   PREDICTED   ACTUAL     DIFF
 1.   4.8870   2.9000   1.9870
 2.  26.0291   5.7000  20.3291
 3.   5.1969   7.7000   2.5031
 4.  14.2701  12.5000   1.7701
 5.   5.1409   4.1000   1.0409
 6.   4.5229   5.3000   0.7771
 7.   5.0878   3.7000   1.3878
 8.  13.3887  14.5000   1.1113
 9.   3.8790   5.7000   1.8210
10.  10.1431  10.1000   0.0431
11.   4.4735   4.5000   0.0265
12.   3.7195   6.1000   2.3805
13.   6.4527   6.9000   0.4473
14.  13.9916  14.1000   0.1084
15.   4.9263   4.5000   0.4263
16.  26.8691  34.1000   7.2309
17.   5.1708  12.5000   7.3292
18.   2.9231   4.1000   1.1769
19.  12.1087   8.5000   3.6087
20.   6.2867   5.3000   0.9867
21.  14.0538  11.3000   2.7538
22.   8.7881  10.5000   1.7119
23.  15.1750  15.3000   0.1250
24.  15.0359  14.9000   0.1359
25.  36.4113  49.5700  13.1587
26.   4.5704   5.3000   0.7296
27.   3.7325   3.7000   0.0325
28.   7.6584   6.5000   1.1584
29.  13.9284  14.1000   0.1716
30.   4.7594   4.9000   0.1406
31.   5.8332   3.7000   2.1332
32.  40.

In [59]:
# Make sure to save the model only after the training has happened!
if len(losses) == epochs:
    torch.save(model.state_dict(), 'TaxiFareRegrModel.pt')
else:
    print('Model has not been trained. Consider loading a trained model instead.')

In [60]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

def haversine_distance(df, lat1, long1, lat2, long2):
    r = 6371
    phi1 = np.radians(df[lat1])
    phi2 = np.radians(df[lat2])
    delta_phi = np.radians(df[lat2]-df[lat1])
    delta_lambda = np.radians(df[long2]-df[long1])
    a = np.sin(delta_phi/2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    return r * c

class TabularModel(nn.Module):
    def __init__(self, emb_size, n_cont, out_sz, layers, p=0.5):
        super().__init__()
        self.embeds = nn.ModuleList([nn.Embedding(ni, nf) for ni,nf in emb_size])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        layerlist = []
        n_emb = sum((nf for ni,nf in emb_size))
        n_in = n_emb + n_cont
        for i in layers:
            layerlist.append(nn.Linear(n_in,i)) 
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
        self.layers = nn.Sequential(*layerlist)
    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        return self.layers(x)

In [62]:
emb_size = [(24, 12), (2, 1), (7, 4)]
model2 = TabularModel(emb_size, 6, 1, [200,100], p=0.4)

In [63]:
model2.load_state_dict(torch.load('TaxiFareRegrModel.pt'));
model2.eval() 

TabularModel(
  (embeds): ModuleList(
    (0): Embedding(24, 12)
    (1): Embedding(2, 1)
    (2): Embedding(7, 4)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=23, out_features=200, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=200, out_features=100, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=100, out_features=1, bias=True)
  )
)

In [64]:
def test_data(mdl): # pass in the name of the new model
    # INPUT NEW DATA
    plat = float(input('What is the pickup latitude?  '))
    plong = float(input('What is the pickup longitude? '))
    dlat = float(input('What is the dropoff latitude?  '))
    dlong = float(input('What is the dropoff longitude? '))
    psngr = int(input('How many passengers? '))
    dt = input('What is the pickup date and time?\nFormat as YYYY-MM-DD HH:MM:SS     ')
    
    # PREPROCESS THE DATA
    dfx_dict = {'pickup_latitude':plat,'pickup_longitude':plong,'dropoff_latitude':dlat,
         'dropoff_longitude':dlong,'passenger_count':psngr,'EDTdate':dt}
    dfx = pd.DataFrame(dfx_dict, index=[0])
    dfx['dist_km'] = haversine_distance(dfx,'pickup_latitude', 'pickup_longitude',
                                        'dropoff_latitude', 'dropoff_longitude')
    dfx['EDTdate'] = pd.to_datetime(dfx['EDTdate'])
    
    # We can skip the .astype(category) step since our fields are small,
    # and encode them right away
    dfx['Hour'] = dfx['EDTdate'].dt.hour
    dfx['AMorPM'] = np.where(dfx['Hour']<12,0,1) 
    dfx['Weekday'] = dfx['EDTdate'].dt.strftime("%a")
    dfx['Weekday'] = dfx['Weekday'].replace(['Fri','Mon','Sat','Sun','Thu','Tue','Wed'],
                                            [0,1,2,3,4,5,6]).astype('int64')
    # CREATE CAT AND CONT TENSORS
    cat_cols = ['Hour', 'AMorPM', 'Weekday']
    cont_cols = ['pickup_latitude', 'pickup_longitude', 'dropoff_latitude',
                 'dropoff_longitude', 'passenger_count', 'dist_km']
    xcats = np.stack([dfx[col].values for col in cat_cols], 1)
    xcats = torch.tensor(xcats, dtype=torch.int64)
    xconts = np.stack([dfx[col].values for col in cont_cols], 1)
    xconts = torch.tensor(xconts, dtype=torch.float)
    
    # PASS NEW DATA THROUGH THE MODEL WITHOUT PERFORMING A BACKPROP
    with torch.no_grad():
        z = mdl(xcats, xconts)
    print(f'\nThe predicted fare amount is ${z.item():.2f}')

In [65]:
z = test_data(model2)

What is the pickup latitude?  40.2
What is the pickup longitude? -73.8
What is the dropoff latitude?  40.12
What is the dropoff longitude? -45.6
How many passengers? 7
What is the pickup date and time?
Format as YYYY-MM-DD HH:MM:SS     2022-05-13 16:12:34

The predicted fare amount is $3966.79
